export const initialState = {
  products: [
    {
      id: 1,
      name: 'Wooden Cup',
      price: '20',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/kitchen/pexels-eva-elijas-6944232.jpg', white: 'images/products/kitchen/pexels-eva-elijas-6944482.jpg'},
      categories: ['NewArrivals', 'Kitchen'],
    },
    {
      id: 2,
      name: 'Ceramic Bowl',
      price: '40',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/kitchen/pexels-eva-elijas-6952245.jpg'},
      categories: ['NewArrivals', 'Kitchen'],
    },
    {
      id: 3,
      name: 'Dotted Ceramic Cups',
      price: '28',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/kitchen/pexels-pavel-danilyuk-7674537.jpg', brown: 'images/products/kitchen/pexels-pavel-danilyuk-7674537.jpg'},
      categories: ['NewArrivals', 'Kitchen'],
    },
    {
      id: 5,
      name: 'Maneki Neko',
      price: '65',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/home/pexels-miguel-á-padriñán-932261.jpg'},
      categories: ['NewArrivals', 'Home'],
    },
    {
      id: 6,
      name: 'Wooden Vase',
      price: '82',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/home/pexels-eva-elijas-6952248.jpg'},
      categories: ['NewArrivals', 'Home'],
    },
    {
      id: 7,
      name: 'Stone Flower Pot',
      price: '40',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/home/pexels-stephanie-ho-993626.jpg'},
      categories: ['NewArrivals', 'Home'],
    },
    {
      id: 8,
      name: 'Clay Flower Vase',
      price: '38',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/home/pexels-tara-winstead-6692129.jpg'},
      categories: ['NewArrivals', 'Home'],
    },
    {
      id: 9,
      name: 'Cotton Socks',
      price: '10',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/fashion/pexels-mikhail-nilov-6968427.jpg', blue: 'images/products/fashion/pexels-alena-shekhovtcova-6995704.jpg'},
      sizes: ['S', 'M', 'L'],
      categories: ['NewArrivals', 'Fashion'],
    },
    {
      id: 10,
      name: 'Linen Set',
      price: '112',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/fashion/pexels-thirdman-6599685.jpg'},
      sizes: ['XS', 'S', 'M', 'L'],
      categories: ['NewArrivals', 'Fashion'],
    },
    {
      id: 11,
      name: 'Cotton Summer Blouse',
      price: '62',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/fashion/pexels-teona-swift-6850609.jpg'},
      sizes: ['XS', 'S', 'M', 'L'],
      categories: ['NewArrivals', 'Fashion'],
    },
    {
      id: 12,
      name: 'Patterened Stationery',
      price: '15',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/craft/pexels-eva-elijas-7967827.jpg', colorful: 'images/products/fashion/pexels-eva-elijas-7967944.jpg'},
      categories: ['NewArrivals', 'Craft'],
    },
    {
      id: 13,
      name: 'Minimalistic Note Set',
      price: '23',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique, massa ut consectetur sagittis, enim ipsum fringilla nibh, ac tempor purus est vestibulum dui. Proin aliquet posuere nisl, vel vestibulum nisl interdum quis. Vestibulum in arcu faucibus, vestibulum magna id, venenatis mauris. Fusce placerat vel eros quis blandit. Donec sed volutpat augue.',
      variants: {main: '/images/products/craft/pexels-polina-kovaleva-8101485.jpg'},
      categories: ['NewArrivals', 'Craft'],
    },
  ],
  orders: [],
};
